default: true

logo_url:
  default: "https://raw.githubusercontent.com/minershive/hiveon-forum-theme/master/assets/hiveos-logo.svg"
  type: string
  description: "This is the source link to your large logo file"

# required:
#     company_short_name: Hiveon